// bootstrap.js — Arrow-MD startup bootstrapper
// Runs BEFORE index.js. Pulls missing core files from the private dev repo,
// then creates .env if it doesn't exist, then launches the bot.
//
// Public repo only ships: index.js, config.js, package.json, bootstrap.js
// Everything else (commands/, lib/, handler.js, dev.js, assets/) is pulled here.

'use strict';

process.on('uncaughtException',  (err) => { console.error('[bootstrap error]', err.message); process.exit(1); });
process.on('unhandledRejection', (err) => { console.error('[bootstrap error]', err?.message); process.exit(1); });

const fs      = require('fs');
const path    = require('path');
const { execSync, spawnSync } = require('child_process');

// ─── CONFIGURE THESE ────────────────────────────────────────────────────────
// The private/full repo that contains commands/, lib/, handler.js, dev.js, assets/
const DEV_REPO = 'https://github.com/YOUR_USERNAME/Arrow-MD-Dev.git';

// Files/folders that must come from the dev repo.
// bootstrap checks if ALL of these exist. If any is missing → pull everything.
const REQUIRED_PATHS = [
  'commands',
  'lib',
  'handler.js',
  'dev.js',
  'assets',
];

// Files that must NEVER be overwritten when pulling (user data / session / config)
const PROTECTED_PATHS = [
  '.env',
  'config.js',
  'baileys_auth',
  'data',
  'node_modules',
  'package-lock.json',
  '.pair_sessions',
  'temp',
];

// Colour helpers
const green  = '\x1b[32m';
const yellow = '\x1b[33m';
const cyan   = '\x1b[36m';
const red    = '\x1b[31m';
const reset  = '\x1b[0m';

const ROOT = process.cwd();

// ─── HELPERS ─────────────────────────────────────────────────────────────────
function log(msg)  { console.log(cyan + '[bootstrap]' + reset + ' ' + msg); }
function ok(msg)   { console.log(green + '✅' + reset + ' ' + msg); }
function warn(msg) { console.log(yellow + '⚠️ ' + reset + ' ' + msg); }
function err(msg)  { console.error(red + '❌' + reset + ' ' + msg); }

function exists(relPath) {
  return fs.existsSync(path.join(ROOT, relPath));
}

function allRequiredExist() {
  return REQUIRED_PATHS.every(p => exists(p));
}

// ─── STEP 1: Pull missing core files from dev repo ──────────────────────────
async function pullDevFiles() {
  if (allRequiredExist()) {
    ok('Core files already present. Skipping pull.');
    return;
  }

  const missing = REQUIRED_PATHS.filter(p => !exists(p));
  warn(`Missing core files: ${missing.join(', ')}`);
  log(`Pulling from dev repo: ${DEV_REPO} …`);

  const tmpDir = path.join(ROOT, '.bootstrap_tmp_' + Date.now());

  try {
    // Shallow clone into a temp dir
    execSync(`git clone --depth 1 ${DEV_REPO} "${tmpDir}"`, {
      stdio: 'pipe',
      timeout: 90_000,
    });

    ok('Cloned dev repo.');

    // Copy only the required paths, skipping anything in PROTECTED_PATHS
    for (const item of REQUIRED_PATHS) {
      const src  = path.join(tmpDir, item);
      const dest = path.join(ROOT, item);

      if (!fs.existsSync(src)) {
        warn(`Dev repo is missing "${item}" — skipping.`);
        continue;
      }

      // Skip if it somehow already exists (double-check safety)
      if (fs.existsSync(dest)) {
        warn(`"${item}" already exists locally — keeping local copy.`);
        continue;
      }

      // Copy
      copyRecursive(src, dest);
      ok(`Copied "${item}".`);
    }

  } catch (e) {
    err(`Failed to pull dev repo: ${e.message}`);
    err('Make sure the repo URL is correct and accessible.');
    process.exit(1);
  } finally {
    // Clean up temp dir
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  }
}

function copyRecursive(src, dest) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const child of fs.readdirSync(src)) {
      copyRecursive(path.join(src, child), path.join(dest, child));
    }
  } else {
    fs.copyFileSync(src, dest);
  }
}

// ─── STEP 2: Create .env if it doesn't exist ────────────────────────────────
function setupEnv() {
  const envPath = path.join(ROOT, '.env');

  if (fs.existsSync(envPath)) {
    ok('.env already exists. Skipping creation.');
    return;
  }

  warn('.env not found. Creating a template .env …');

  const template = `# Arrow-MD Environment Variables
# Generated by bootstrap.js on ${new Date().toISOString()}
#
# HOW TO GET YOUR SESSION ID:
#   1. Visit https://devkevo-arrow-md-pair-site.hf.space
#   2. Pair your WhatsApp number
#   3. Copy the session ID (starts with Arrow-MD≈)
#   4. Paste it below

SESSION_ID=

# Optional: override owner number here (leave blank to use config.js default)
# OWNER_NUMBER=

# Optional: timezone (default is Africa/Nairobi)
# TZ=Africa/Nairobi
`;

  fs.writeFileSync(envPath, template, 'utf8');

  console.log('');
  console.log(yellow + '┌─────────────────────────────────────────────────────┐' + reset);
  console.log(yellow + '│  📄  .env file created!                             │' + reset);
  console.log(yellow + '│                                                     │' + reset);
  console.log(yellow + '│  ACTION REQUIRED:                                   │' + reset);
  console.log(yellow + '│  1. Open .env in a text editor                      │' + reset);
  console.log(yellow + '│  2. Add your SESSION_ID (starts with Arrow-MD≈)     │' + reset);
  console.log(yellow + '│  3. Run the bot again: node bootstrap.js            │' + reset);
  console.log(yellow + '│                                                     │' + reset);
  console.log(yellow + '│  Get session: https://devkevo-arrow-md-pair-site.hf.space │' + reset);
  console.log(yellow + '└─────────────────────────────────────────────────────┘' + reset);
  console.log('');

  // Don't exit — let the bot start anyway; session check in index.js will
  // catch the missing SESSION_ID with its own clear error message.
}

// ─── STEP 3: Install dependencies if node_modules is missing ────────────────
function ensureDependencies() {
  if (exists('node_modules') && exists('node_modules/.package-lock.json') || 
      exists('node_modules') && fs.readdirSync(path.join(ROOT, 'node_modules')).length > 5) {
    return; // Already installed
  }

  log('node_modules not found or empty. Running npm install …');
  try {
    execSync('npm install --production', {
      stdio: 'inherit',
      timeout: 300_000,
      cwd: ROOT,
    });
    ok('Dependencies installed.');
  } catch (e) {
    warn(`npm install encountered issues: ${e.message}`);
    warn('Continuing anyway — some features may not work.');
  }
}

// ─── MAIN ────────────────────────────────────────────────────────────────────
async function main() {
  console.log('');
  console.log(green + '╔══════════════════════════════════════════╗' + reset);
  console.log(green + '║       🚀  Arrow-MD Bootstrap  🚀         ║' + reset);
  console.log(green + '╚══════════════════════════════════════════╝' + reset);
  console.log('');

  // 1. Pull missing files from dev repo
  await pullDevFiles();

  // 2. Create .env if missing
  setupEnv();

  // 3. Ensure node_modules
  ensureDependencies();

  // 4. Verify all required paths now exist before handing off
  if (!allRequiredExist()) {
    const stillMissing = REQUIRED_PATHS.filter(p => !exists(p));
    err(`Still missing after pull: ${stillMissing.join(', ')}`);
    err('Cannot start. Please check your DEV_REPO URL in bootstrap.js.');
    process.exit(1);
  }

  // 5. Launch the actual bot
  console.log('');
  log('All files present. Launching bot …');
  console.log('');

  // Hand off by requiring index.js in the same process
  // (avoids spawning a child process and keeps PID management simple)
  require('./index.js');
}

main().catch((e) => {
  err('Bootstrap failed: ' + e.message);
  process.exit(1);
});
