// index.js — Arrow-MD unified entry point
// Bootstrap (file pull, .env setup, dependency check) runs first,
// then the WhatsApp connection is established — all in one process.

'use strict';

process.on('uncaughtException',  (err) => console.error('[uncaughtException]', err.message));
process.on('unhandledRejection', (err) => console.error('[unhandledRejection]', err?.message));

// Raise the global EventEmitter listener limit.
require('events').defaultMaxListeners = 50;

// Suppress noisy Baileys internal signal protocol logs
const _origStderr = process.stderr.write.bind(process.stderr);
process.stderr.write = (chunk, ...args) => {
  const str = chunk.toString();
  const noisy = [
    'Closing open session', 'Closing session:', 'SessionEntry', '_chains',
    'chainType', 'messageKeys', 'rootKey', 'indexInfo', 'baseKey',
    'remoteIdentityKey', 'previousCounter', 'chainKey', 'registrationId',
    'currentRatchet', 'ephemeralKeyPair', 'prekey bundle', '<Buffer',
    'Bad MAC', 'Session error', 'doDecryptWhisperMessage', 'verifyMAC',
    'SessionCipher', 'decryptWithSessions', 'session_cipher',
    '_asyncQueueExecutor', 'queue_job',
  ];
  if (noisy.some(s => str.includes(s))) return true;
  return _origStderr(chunk, ...args);
};

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// ─── BOOTSTRAP CONFIG ────────────────────────────────────────────────────────
// The private/full repo that contains commands/, lib/, handler.js, dev.js, assets/
const DEV_REPO = 'https://github.com/Kevo-254-ke/arrow.git';

const REQUIRED_PATHS = [
  'commands',
  'lib',
  'handler.js',
  'dev.js',
  'assets',
];

const PROTECTED_PATHS = [
  '.env',
  'config.js',
  'baileys_auth',
  'data',
  'node_modules',
  'package-lock.json',
  '.pair_sessions',
  'temp',
];

const green  = '\x1b[32m';
const yellow = '\x1b[33m';
const cyan   = '\x1b[36m';
const red    = '\x1b[31m';
const reset  = '\x1b[0m';

const ROOT = process.cwd();

// ─── BOOTSTRAP HELPERS ───────────────────────────────────────────────────────
function bLog(msg)  { console.log(cyan  + '[bootstrap]' + reset + ' ' + msg); }
function bOk(msg)   { console.log(green + '✅' + reset + ' ' + msg); }
function bWarn(msg) { console.log(yellow + '⚠️ ' + reset + ' ' + msg); }
function bErr(msg)  { console.error(red + '❌' + reset + ' ' + msg); }

function exists(relPath) {
  return fs.existsSync(path.join(ROOT, relPath));
}

function allRequiredExist() {
  return REQUIRED_PATHS.every(p => exists(p));
}

function copyRecursive(src, dest) {
  const stat = fs.statSync(src);
  if (stat.isDirectory()) {
    fs.mkdirSync(dest, { recursive: true });
    for (const child of fs.readdirSync(src)) {
      copyRecursive(path.join(src, child), path.join(dest, child));
    }
  } else {
    fs.copyFileSync(src, dest);
  }
}

// ─── STEP 1: Pull missing core files from dev repo ──────────────────────────
async function pullDevFiles() {
  if (allRequiredExist()) {
    bOk('Core files already present. Skipping pull.');
    return;
  }

  const missing = REQUIRED_PATHS.filter(p => !exists(p));
  bWarn(`Missing core files: ${missing.join(', ')}`);
  bLog(`Pulling from dev repo: ${DEV_REPO} …`);

  const tmpDir = path.join(ROOT, '.bootstrap_tmp_' + Date.now());

  try {
    execSync(`git clone --depth 1 ${DEV_REPO} "${tmpDir}"`, {
      stdio: 'pipe',
      timeout: 90_000,
    });

    bOk('Cloned dev repo.');

    for (const item of REQUIRED_PATHS) {
      const src  = path.join(tmpDir, item);
      const dest = path.join(ROOT, item);

      if (!fs.existsSync(src)) {
        bWarn(`Dev repo is missing "${item}" — skipping.`);
        continue;
      }

      if (fs.existsSync(dest)) {
        bWarn(`"${item}" already exists locally — keeping local copy.`);
        continue;
      }

      copyRecursive(src, dest);
      bOk(`Copied "${item}".`);
    }

  } catch (e) {
    bErr(`Failed to pull dev repo: ${e.message}`);
    bErr('Make sure the repo URL is correct and accessible.');
    process.exit(1);
  } finally {
    try { fs.rmSync(tmpDir, { recursive: true, force: true }); } catch {}
  }
}

// ─── STEP 2: Create .env if it doesn't exist ────────────────────────────────
function setupEnv() {
  const envPath = path.join(ROOT, '.env');

  if (fs.existsSync(envPath)) {
    bOk('.env already exists. Skipping creation.');
    return;
  }

  bWarn('.env not found. Creating a template .env …');

  const template = `# Arrow-MD Environment Variables
# Generated by index.js on ${new Date().toISOString()}
#
# HOW TO GET YOUR SESSION ID:
#   1. Visit https://devkevo-arrow-md-pair-site.hf.space
#   2. Pair your WhatsApp number
#   3. Copy the session ID (starts with Arrow-MD≈)
#   4. Paste it below

SESSION_ID=
`;

  fs.writeFileSync(envPath, template, 'utf8');

  console.log('');
  console.log(yellow + '┌─────────────────────────────────────────────────────┐' + reset);
  console.log(yellow + '│  📄  .env file created!                             │' + reset);
  console.log(yellow + '│                                                     │' + reset);
  console.log(yellow + '│  ACTION REQUIRED:                                   │' + reset);
  console.log(yellow + '│  1. Open .env in a text editor                      │' + reset);
  console.log(yellow + '│  2. Add your SESSION_ID (starts with Arrow-MD≈)     │' + reset);
  console.log(yellow + '│  3. Run the bot again: node index.js                │' + reset);
  console.log(yellow + '│                                                     │' + reset);
  console.log(yellow + '│  Get session: https://devkevo-arrow-md-pair-site.hf.space │' + reset);
  console.log(yellow + '└─────────────────────────────────────────────────────┘' + reset);
  console.log('');
}

// ─── STEP 3: Install dependencies if node_modules is missing ────────────────
function ensureDependencies() {
  const nmDir = path.join(ROOT, 'node_modules');
  const hasNodeModules =
    fs.existsSync(nmDir) &&
    (fs.existsSync(path.join(nmDir, '.package-lock.json')) ||
      fs.readdirSync(nmDir).length > 5);

  if (hasNodeModules) return;

  bLog('node_modules not found or empty. Running npm install …');
  try {
    execSync('npm install --production', {
      stdio: 'inherit',
      timeout: 300_000,
      cwd: ROOT,
    });
    bOk('Dependencies installed.');
  } catch (e) {
    bWarn(`npm install encountered issues: ${e.message}`);
    bWarn('Continuing anyway — some features may not work.');
  }
}

// ─── BOOTSTRAP MAIN ──────────────────────────────────────────────────────────
async function bootstrap() {
  console.log('');
  console.log(green + '╔══════════════════════════════════════════╗' + reset);
  console.log(green + '║       🚀  Arrow-MD Bootstrap  🚀         ║' + reset);
  console.log(green + '╚══════════════════════════════════════════╝' + reset);
  console.log('');

  await pullDevFiles();
  setupEnv();
  ensureDependencies();

  if (!allRequiredExist()) {
    const stillMissing = REQUIRED_PATHS.filter(p => !exists(p));
    bErr(`Still missing after pull: ${stillMissing.join(', ')}`);
    bErr('Cannot start. Please check your DEV_REPO URL in index.js.');
    process.exit(1);
  }

  console.log('');
  bLog('All files present. Launching bot …');
  console.log('');
}

// ─── BOT: Auth folder cleaner ────────────────────────────────────────────────
function cleanAuthFolder() {
  const authDir = path.join(ROOT, 'baileys_auth');

  if (!fs.existsSync(authDir)) return;

  try {
    for (const file of fs.readdirSync(authDir)) {
      if (file === 'creds.json') continue;
      const filePath = path.join(authDir, file);
      const stat = fs.statSync(filePath);
      if (stat.isDirectory()) {
        fs.rmSync(filePath, { recursive: true, force: true });
      } else {
        fs.unlinkSync(filePath);
      }
    }
  } catch {}
}

// ─── BOT: Session restore ────────────────────────────────────────────────────
async function autoRestoreSession(config, decodeSession) {
  console.log('\n' + green + '╔══════════════════════════════════════════════╗' + reset);
  console.log(green        + '║         🔐  SESSION INITIALIZATION  🔐        ║' + reset);
  console.log(green        + '╚══════════════════════════════════════════════╝' + reset);

  if (!config.sessionID || config.sessionID.trim() === '') {
    console.log(yellow + '\n⚠️  No session ID found in config.js' + reset);
    console.log('💡 Add your session ID to config.js: sessionID: "Arrow-MD≈..."');
    process.exit(1);
  }

  if (!config.sessionID.startsWith('Arrow-MD≈')) {
    console.log(red + '\n❌ Invalid session ID format.' + reset);
    console.log('💡 Session ID must start with "Arrow-MD≈"');
    process.exit(1);
  }

  console.log('\n🔐 Restoring session...');
  try {
    decodeSession(config.sessionID);
    console.log(green + '✅ Session restored.' + reset);
  } catch (e) {
    console.error(red + '❌ Failed to restore session:' + reset, e.message);
    process.exit(1);
  }
}

// ─── BOT: WhatsApp connection ─────────────────────────────────────────────────
async function connectToWhatsApp() {
  // These requires are deferred until after bootstrap guarantees the files exist
  const {
    default: makeWASocket,
    useMultiFileAuthState,
    fetchLatestBaileysVersion,
  } = require('@whiskeysockets/baileys');
  const pino = require('pino');

  const { setSock }                                    = require('./lib/permissions');
  const { loadCommands }                               = require('./lib/loader');
  const { handleMessage }                              = require('./handler');
  const store                                          = require('./lib/store');
  const activity                                       = require('./lib/activity');
  const { registerAntiFeatures }                       = require('./lib/antifeatures');
  const { hasSession, decodeSession }                  = require('./lib/session');
  const { registerConnectionEvents, joinSupportGroup } = require('./lib/connection');
  const { handleGroupParticipants }                    = require('./lib/groupEvents');
  const config                                         = require('./config');

  cleanAuthFolder();

  if (!hasSession()) {
    await autoRestoreSession(config, decodeSession);
  } else {
    console.log('\n✅ Session found. Starting...\n');
  }

  activity.purgeOld(7);

  const commands = loadCommands();

  const { state, saveCreds } = await useMultiFileAuthState('baileys_auth');

  const FALLBACK_VERSION = [2, 3000, 1023059264];
  let version = FALLBACK_VERSION;
  try {
    const result = await Promise.race([
      fetchLatestBaileysVersion(),
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error('timeout')), 10_000)
      ),
    ]);
    version = result.version ?? FALLBACK_VERSION;
    console.log(`✅ WA version: ${version.join('.')}`);
  } catch {
    console.log(`⚠️  Could not fetch WA version — using fallback ${FALLBACK_VERSION.join('.')}`);
  }

  const sock = makeWASocket({
    version,
    auth: state,
    printQRInTerminal: false,
    logger: pino({ level: 'silent' }).child({ level: 'silent' }),
    browser: ['Ubuntu', 'Chrome', '20.0.0'],
    syncFullHistory: false,
    defaultQueryTimeoutMs: undefined,
    getMessage: async () => undefined,
  });

  store.setSocket(sock);
  setSock(sock);
  sock.ev.on('contacts.update', () => setSock(sock));
  sock.ev.on('contacts.upsert', () => setSock(sock));

  registerAntiFeatures(sock);
  registerConnectionEvents(sock, connectToWhatsApp);

  sock.ev.on('messages.upsert', (msg) => handleMessage(sock, commands, msg));
  sock.ev.on('messages.upsert', () => joinSupportGroup(sock));

  sock.ev.on('messages.upsert', ({ messages }) => {
    for (const m of messages) {
      if (!m.message || m.key.fromMe) continue;
      if (!m.key.remoteJid?.endsWith('@g.us')) continue;
      const sender = m.key.participant || m.key.remoteJid;
      if (sender) activity.record(m.key.remoteJid, sender);
    }
  });

  sock.ev.on('messages.update', (updates) => {
    for (const { key, update } of updates) {
      if (!key.remoteJid?.endsWith('@g.us')) continue;
      if (update.reaction !== undefined || update.reactions) {
        activity.record(key.remoteJid, key.participant || key.remoteJid);
      }
    }
  });

  sock.ev.on('group-participants.update', (update) => handleGroupParticipants(sock, update));
  sock.ev.on('creds.update', saveCreds);
}

// ─── ENTRY POINT ─────────────────────────────────────────────────────────────
async function main() {
  await bootstrap();
  await connectToWhatsApp();
}

main().catch((err) => {
  console.error('💥 Fatal error:', err);
  process.exit(1);
});